services:
  pr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-python
    env_file: .env    
    ports:
      - '8082:8082'
    networks:
      - pr_default

networks:
  pr_default:
    driver: bridge
